server:
  port: ${SERVER_PORT:8082}

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${EUREKA_HOSTNAME:localhost}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecomera_product}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes
      cache-null-values: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs


logging:
  level:
    com.ecomera.product: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  signing-key: ${JWT_SECRET_KEY}
  access-token-ttl: ${JWT_ACCESS_TTL:3600000}
  refresh-token-ttl: ${JWT_REFRESH_TTL:604800000}

cors:
  allowed-origins:
    - http://localhost:4200 # Angular
    - http://localhost:3000 # React
    - http://localhost:5173 # Vite
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true

management:
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches