server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecomera_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: ${LIQUIBASE_ENABLED:true}


jwt:
  signing-key: ${JWT_SECRET_KEY}
  access-token-ttl: ${JWT_ACCESS_TTL:3600000}
  refresh-token-ttl: ${JWT_REFRESH_TTL:604800000}

cors:
  allowed-origins:
    - http://localhost:4200
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics